### ISSUE TITLE
Use same text style in popups than text editor

### ISSUE THREAD

**Issue by jvican** [sublimelsp/LSP#1560]
**Describe the bug**
It looks like Sublime is using different text styles than the text editor to show popups, which results in way too big font sizes and different font families used.

**To Reproduce**
1. Install latest Discord exclusive beta 4095
2. Install LSP
3. Hover a type or term to get documentation about it
4. See different text style

**Expected behavior**
I expect LSP to reuse the same text style I've configured for my text editor.

**Screenshots**
<img width="865" alt="Screen Shot 2021-01-25 at 9 25 05 AM" src="https://user-images.githubusercontent.com/2462974/106000252-e9526800-60ae-11eb-9229-fa6935c6ec14.png">

**Environment (please complete the following information):**
- OS: macOS Big Sur 11.11
- Sublime Text version: 4095
- LSP version: 1.2.8
- Language servers used: Metals

**Comment by rwols** [comment]
The backend for popups is [mdpopups](https://github.com/facelessuser/sublime-markdown-popups). It allows customization of some css elements. The default location for this css override file Packages/User/mdpopups.css, although you can change that with a setting.

To get the same font in the popup as your `"font_face"` setting in Packages/User/Preferences.sublime-settings, create the file Packages/User/mdpopups.css and write the following into it:

```css
html {
    --mdpopups-font-mono: "your desired font face";
}
```

After you make a change in this file, restart Sublime Text.

**Comment by jfcherng** [comment]
This won't work since LSP defines a more precise CSS selector in https://github.com/sublimelsp/LSP/blob/74c58118e6837e7761dbd63e31ea9e83249bbd4a/popups.css#L1-L4.

```css
html .lsp_popup {
    font-family: "Ubuntu Mono";
    --mdpopups-font-mono: "Ubuntu Mono";
}
```
works for me.

**Comment by tukusejssirs** [comment]
I wanted to change the font size and family as well, but it doesn’t work for me.

I simply created file `~/.config/sublime-text/Packages/User/mdpopups.css` with the following contents:

```css
html .lsp_popup {
  font-family: 'Ubuntu Mono';
  font-size: 12pt;
  --mdpopups-font-mono: 'Ubuntu Mono';
}
```

The reason why it failed to load the CSS was that I used tabs for indentation and single quotes instead of double quotes (both are valid for CSS in general and prefer this style instead of space indentation and double quotes). When replaced tabs with spaces and single quotes with double quotes, some parts worked as expected, some not.

So I looked at [`popups.css`](https://github.com/sublimelsp/LSP/blob/74c58118e6837e7761dbd63e31ea9e83249bbd4a/popups.css) file and I found that `.actions` are still using `system` font.

https://github.com/sublimelsp/LSP/blob/74c58118e6837e7761dbd63e31ea9e83249bbd4a/popups.css#L53-L54

So my final CSS looks like this:

```css
html .lsp_popup, html .actions {
  font-family: "Ubuntu Mono";
  font-size: 12pt;
  --mdpopups-font-mono: "Ubuntu Mono";
}
```

I still hope that we could use the very same font size and family as in files open in ST, as when I change the font size and/or family, now I need to remember to change it in two places (which I might forget).

---

Related: facelessuser/sublime-markdown-popups#28 (and my [comment](https://github.com/facelessuser/sublime-markdown-popups/issues/28#issuecomment-1192944271))

**Comment by AndydeCleyre** [comment]
Is the above example, repeated here, still expected to work these days? I haven't been able to get the code blocks in popups to use my chosen font family.

`~/.config/sublime-text/Packages/User/mdpopups.css`:

```css
html .lsp_popup, html .actions {
  font-family: "Ubuntu Mono";
  font-size: 12pt;
  --mdpopups-font-mono: "Ubuntu Mono";
}
```
