### ISSUE TITLE
How can I change the color of this?

### ISSUE THREAD

**Issue by maclam** [sublimelsp/LSP#2255]
**Is your feature request related to a problem? Please describe.**
I didn't find anything in your documentation to change this part in white, or maybe I am blind?
It's annoying because it's unreadable, I would like to keep the background yellow for the warnings.

![unreadable](https://github.com/sublimelsp/LSP/assets/22882318/d322392d-e2f6-4b30-b25f-29c57ba19909)

Here is my mdpopups.css file:
```css
html.dark {
    background-color: #252525;
    color: #9f9f9f;
}

.dark .mdpopups .highlight {
    background-color: #0f0f0f;
}

html.light {
    background-color: #e5e5e5;
    color: #666666;
}

.light .mdpopups .highlight {
    background-color: #fff;
}

html {
    --mdpopups-font-mono: "Operator Mono Book";
}

.errors a,
.warnings a {
    display: block;
    color: #010192;
    margin-top: 0.5rem;
}

.lsp_popup .errors {
    border-width: 0;
    background-color: #fd3434;
    color: #0f0f0f;
    margin-bottom: 0.5rem;
    padding: 0.5rem;
}

.lsp_popup .warnings {
    border-width: 0;
    background-color: #feff60;
    color: #0f0f0f;
    margin-bottom: 0.5rem;
    padding-top: 0.5rem;
}

.lsp_popup .info {
    border-width: 0;
    background-color: #00bfff;
    color: #0f0f0f;
    margin-bottom: 0.5rem;
    padding-top: 0.5rem;
}

.lsp_popup .hints {
    border-width: 0;
    background-color: #f8f8f8;
    color: #0f0f0f;
    margin-bottom: 0.5rem;
    padding-top: 0.5rem;
}


``` 

**Describe the solution you'd like**
Add an option to be able to modify this color if possible.

Thank you very much and again for your hard work 🙏.
